;***************************************************************
;** Lista de macros das System Calls de 64-bit (x86-64) Linux **
;***************************************************************
%assign accept                 43 
%assign accept4                288
%assign access                 21 
%assign acct                   163
%assign add_key                248
%assign adjtimex               159
%assign afs_syscall            183
%assign alarm                  37 
%assign arch_prctl             158
%assign bind                   49 
%assign brk                    12 
%assign capget                 125 
%assign capset                 126 
%assign chdir                  80  
%assign chmod                  90  
%assign chown                  92  
%assign chroot                 161 
%assign clock_getres           229 
%assign clock_gettime          228 
%assign clock_nanosleep        230 
%assign clock_settime          227 
%assign clone                  56  
%assign close                  3   
%assign connect                42  
%assign creat                  85  
%assign create_module          174 
%assign delete_module          176 
%assign dup                    32  
%assign dup2                   33  
%assign dup3                   292 
%assign epoll_create           213 
%assign epoll_create1          291 
%assign epoll_ctl              233 
%assign epoll_ctl_old          214 
%assign epoll_pwait            281 
%assign epoll_wait             232 
%assign epoll_wait_old         215 
%assign eventfd                284 
%assign eventfd2               290 
%assign execve                 59  
%assign exit                   60  
%assign exit_group             231 
%assign faccessat              269 
%assign fadvise64              221 
%assign fallocate              285 
%assign fanotify_init          300 
%assign fanotify_mark          301 
%assign fchdir                 81  
%assign fchmod                 91  
%assign fchmodat               268 
%assign fchown                 93  
%assign fchownat               260 
%assign fcntl                  72  
%assign fdatasync              75  
%assign fgetxattr              193 
%assign flistxattr             196 
%assign flock                  73  
%assign fork                   57  
%assign fremovexattr           199 
%assign fsetxattr              190 
%assign fstat                  5   
%assign fstatfs                138 
%assign fsync                  74  
%assign ftruncate              77  
%assign futex                  202 
%assign futimesat              261 
%assign get_kernel_syms        177 
%assign get_mempolicy          239 
%assign get_robust_list        274 
%assign get_thread_area        211 
%assign getcwd                 79  
%assign getdents               78  
%assign getdents64             217 
%assign getegid                108 
%assign geteuid                107 
%assign getgid                 104 
%assign getgroups              115 
%assign getitimer              36  
%assign getpeername            52  
%assign getpgid                121 
%assign getpgrp                111 
%assign getpid                 39  
%assign getpmsg                181 
%assign getppid                110 
%assign getpriority            140 
%assign getresgid              120 
%assign getresuid              118 
%assign getrlimit              97  
%assign getrusage              98  
%assign getsid                 124 
%assign getsockname            51  
%assign getsockopt             55  
%assign gettid                 186 
%assign gettimeofday           96  
%assign getuid                 102 
%assign getxattr               191 
%assign init_module            175 
%assign inotify_add_watch      254 
%assign inotify_init           253 
%assign inotify_init1          294 
%assign inotify_rm_watch       255 
%assign io_cancel              210 
%assign io_destroy             207 
%assign io_getevents           208 
%assign io_setup               206 
%assign io_submit              209 
%assign ioctl                  16  
%assign ioperm                 173 
%assign iopl                   172 
%assign ioprio_get             252 
%assign ioprio_set             251 
%assign kexec_load             246 
%assign keyctl                 250 
%assign kill                   62  
%assign lchown                 94  
%assign lgetxattr              192 
%assign link                   86  
%assign linkat                 265 
%assign listen                 50  
%assign listxattr              194 
%assign llistxattr             195 
%assign lookup_dcookie         212 
%assign lremovexattr           198 
%assign lseek                  8   
%assign lsetxattr              189 
%assign lstat                  6   
%assign madvise                28  
%assign mbind                  237 
%assign migrate_pages          256 
%assign mincore                27  
%assign mkdir                  83  
%assign mkdirat                258 
%assign mknod                  133 
%assign mknodat                259 
%assign mlock                  149 
%assign mlockall               151 
%assign mmap                   9   
%assign modify_ldt             154 
%assign mount                  165 
%assign move_pages             279 
%assign mprotect               10  
%assign mq_getsetattr          245 
%assign mq_notify              244 
%assign mq_open                240 
%assign mq_timedreceive        243 
%assign mq_timedsend           242 
%assign mq_unlink              241 
%assign mremap                 25  
%assign msgctl                 71  
%assign msgget                 68  
%assign msgrcv                 70  
%assign msgsnd                 69  
%assign msync                  26  
%assign munlock                150 
%assign munlockall             152 
%assign munmap                 11  
%assign nanosleep              35  
%assign newfstatat             262 
%assign nfsservctl             180 
%assign open                   2   
%assign openat                 257 
%assign pause                  34  
%assign perf_event_open        298 
%assign personality            135 
%assign pipe                   22  
%assign pipe2                  293 
%assign pivot_root             155 
%assign poll                   7   
%assign ppoll                  271 
%assign prctl                  157 
%assign pread64                17  
%assign preadv                 295 
%assign prlimit64              302 
%assign pselect6               270 
%assign ptrace                 101 
%assign putpmsg                182 
%assign pwrite64               18  
%assign pwritev                296 
%assign query_module           178 
%assign quotactl               179 
%assign read                   0   
%assign readahead              187 
%assign readlink               89  
%assign readlinkat             267 
%assign readv                  19  
%assign reboot                 169 
%assign recvfrom               45  
%assign recvmmsg               299 
%assign recvmsg                47  
%assign remap_file_pages       216 
%assign removexattr            197 
%assign rename                 82  
%assign renameat               264 
%assign request_key            249 
%assign restart_syscall        219 
%assign rmdir                  84  
%assign rt_sigaction           13  
%assign rt_sigpending          127 
%assign rt_sigprocmask         14  
%assign rt_sigqueueinfo        129 
%assign rt_sigreturn           15  
%assign rt_sigsuspend          130 
%assign rt_sigtimedwait        128 
%assign rt_tgsigqueueinfo      297 
%assign sched_get_priority_max 146 
%assign sched_get_priority_min 147 
%assign sched_getaffinity      204 
%assign sched_getparam         143 
%assign sched_getscheduler     145 
%assign sched_rr_get_interval  148 
%assign sched_setaffinity      203 
%assign sched_setparam         142 
%assign sched_setscheduler     144 
%assign sched_yield            24  
%assign security               185 
%assign select                 23  
%assign semctl                 66  
%assign semget                 64  
%assign semop                  65  
%assign semtimedop             220 
%assign sendfile               40  
%assign sendmsg                46  
%assign sendto                 44  
%assign set_mempolicy          238 
%assign set_robust_list        273 
%assign set_thread_area        205 
%assign set_tid_address        218 
%assign setdomainname          171 
%assign setfsgid               123 
%assign setfsuid               122 
%assign setgid                 106 
%assign setgroups              116 
%assign sethostname            170 
%assign setitimer              38  
%assign setpgid                109 
%assign setpriority            141 
%assign setregid               114 
%assign setresgid              119 
%assign setresuid              117 
%assign setreuid               113 
%assign setrlimit              160 
%assign setsid                 112 
%assign setsockopt             54  
%assign settimeofday           164 
%assign setuid                 105 
%assign setxattr               188 
%assign shmat                  30  
%assign shmctl                 31  
%assign shmdt                  67  
%assign shmget                 29  
%assign shutdown               48  
%assign sigaltstack            131 
%assign signalfd               282 
%assign signalfd4              289 
%assign socket                 41  
%assign socketpair             53  
%assign splice                 275 
%assign stat                   4   
%assign statfs                 137 
%assign swapoff                168 
%assign swapon                 167 
%assign symlink                88  
%assign symlinkat              266 
%assign sync                   162 
%assign sync_file_range        277 
%assign _sysctl                156 
%assign sysfs                  139 
%assign sysinfo                99  
%assign syslog                 103 
%assign tee                    276 
%assign tgkill                 234 
%assign time                   201 
%assign timer_create           222 
%assign timer_delete           226 
%assign timer_getoverrun       225 
%assign timer_gettime          224 
%assign timer_settime          223 
%assign timerfd_create         283 
%assign timerfd_gettime        287 
%assign timerfd_settime        286 
%assign times                  100 
%assign tkill                  200 
%assign truncate               76  
%assign tuxcall                184 
%assign umask                  95  
%assign umount2                166 
%assign uname                  63  
%assign unlink                 87  
%assign unlinkat               263 
%assign unshare                272 
%assign uselib                 134 
%assign ustat                  136 
%assign utime                  132 
%assign utimensat              280 
%assign utimes                 235 
%assign vfork                  58  
%assign vhangup                153 
%assign vmsplice               278 
%assign vserver                236 
%assign wait4                  61  
%assign waitid                 247 
%assign write                  1   
%assign writev                 20  
